---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Pull mini-project image
      docker_image:
        name: shmfaraz15/mini-project
        source: pull

    - name: starting docker container
      command: docker run -it -d shmfaraz15/mini-project
#
#    - name: Execute commands in docker container
#      command: docker exec -it user33 bash -c 'echo "Hello remote machine"'
#    - name: Start terminal on remote machine
#      shell:
#      args:
#        cmd: DISPLAY=:0 nohup gnome-terminal -e "bash -c 'whoami'" </dev/null >/dev/null 2>&1 &
#        executable: /bin/bash
