---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Pull mini-project image
      docker_image:
        name: shmfaraz15/mini-project
        source: pull
    - name: Start terminal on remote machine
      shell:
      args:
        cmd: DISPLAY=:0 nohup gnome-terminal
        executable: /bin/bash